- src/features/export/export_feature.py
- src/features/export/use_cases/export_use_case.py
- src/services/document_service.py
- src/tests/bdd/export_package.feature
- src/tests/bdd/steps/handle_response.py
update the export use case (fix security issues, add create_response declarator and delete temp folders on the DMSS host with a background task)
Start to facilitate functionality for exporting documents. later, this export endpoint will handle adding meta information to exported documents.
closes #285
> fix: update export endpoint

- .github/workflows/checks.yml
- generate-python-package.sh
- src/app.py
- src/common/responses.py
- src/domain_classes/blueprint.py
- src/domain_classes/lookup.py
- src/domain_classes/storage_recipe.py
- src/domain_classes/tree_node.py
- src/domain_classes/ui_recipe.py
- src/enums.py
- src/features/lookup_table/lookup_table_feature.py
- src/features/lookup_table/use_cases/create_lookup_table.py
- src/home/system/SIMOS/StorageAttribute.json
- src/restful/request_types/shared.py
- src/services/database.py
- src/storage/data_source_class.py
- src/storage/internal/lookup_tables.py
- src/tests/bdd/create_lookup.feature
- src/tests/unit/mock_blueprint_provider.py
- src/tests/unit/test_data_source_and_repositories.py
- New endpoint `POST lookup/myNewLookup`
- Update `create_response` to accept no response_class. Needed for responses with no content
- Refactor StorageRecipe and StorageAttribute to be pydantic classes. Needed for use in validation.
- Rename "StorageAttribute" `storageTypeAffinity` -> `storageAffintiy` to be consistent with "StorageRecipes"
- Recipes should be taken out of the Blueprints, must be available for DMSS, and are application specific. 
closes #282
> feature: create lookup tables

- src/common/utils/package_import.py
- src/domain_classes/lookup.py
- src/enums.py
- src/features/lookup_table/lookup_table_feature.py
- src/features/lookup_table/use_cases/create_lookup_table.py
- src/home/system/SIMOS/RecipeLink.json
- src/home/system/SIMOS/recipe_links/blueprint.json
- src/storage/internal/lookup_tables.py
- src/tests/bdd/create_lookup.feature
- New feature: Create a lookup table by pointing to a package and giving it a name.
- DMSS will go through that package, gathering all "RecipeLinks", and generate a recipe lookup stored in a internal database
- Fixed a bug in import causing a "name" attribute requirement for all documents 
- Recipes will be moved out of blueprints. A lookup per. application is needed.
fixes #292
> feature: generate recipe lookup from imported folders

- src/domain_classes/tree_node.py
- src/features/export/use_cases/export_use_case.py
- src/storage/repositories/zip.py
include package json file with package meta info when exporting.
handle 3 cases when exporting:
1) single file
2) root package
3) non root package
non root pacakge is not yet supported. will add functionality for this later
support export feature
closes #286
> fix: include package json file with package meta info when exporting

- src/common/tree_node_serializer.py
- src/domain_classes/tree_node.py
- src/features/document/use_cases/get_document_by_path_use_case.py
- src/services/document_service.py
- src/tests/unit/test_add_file_to_package_use_case.py
- src/tests/unit/test_data_source_and_repositories.py
- src/tests/unit/test_get.py
- src/tests/unit/test_save.py
- src/tests/unit/test_tree_error_node.py
- src/tests/unit/test_tree_node_helpers.py
- Move the logic from "DictImporter" and "DictExporter" to simple functions in a separate file
- Remove the Node.to_dict() functions  - To avoid circular dependencies and simpler to have ONE way to serialize Nodes
- More maintainable code base
closes #313
> refactor: tree node serializer to separate file, and no longer a class

- src/domain_classes/lookup.py
- src/features/lookup_table/use_cases/create_lookup_table.py
- src/home/system/SIMOS/recipe_links/pdf.json
- src/tests/unit/test_extend_recipe_links.py
- Adds "realize_extends" functionality to the "Lookup" class
- Call this once when a new lookup is created, before it is saved
closes #302
> feature: extend RecipeLinks on lookup creation

- generate-python-package.sh
roll back openapi generator version, since V6 caused some breaking changes
> chore: roll back openapi generator version

- .github/CODEOWNERS
- src/common/utils/get_storage_recipe.py
- src/domain_classes/ui_recipe.py
- src/features/blueprint/use_cases/get_blueprint_use_case.py
- src/tests/bdd/get_blueprints.feature
Fix a bug where builtin default ui-recipes where not used if a context were specified and no recipes found.
> fix: builtin default ui recipes not used if there is a context

- src/domain_classes/lookup.py
- src/features/blueprint/use_cases/get_blueprint_use_case.py
- src/features/lookup_table/use_cases/create_lookup_table.py
- src/home/system/SIMOS/RecipeLink.json
- RecipeLinks and Lookups now support "initialRecipe"
- Initial recipe can be used to select a single plugin as a entrypoint for the UI
closes #335
> feature: lookup and getBlueprint serves 'initialRecipe's

- src/services/database.py
- src/storage/internal/lookup_tables.py
- src/tests/bdd/create_lookup.feature
- allow updating/replacing recipe lookups
- Removes the need to reset entire dmss for updating a lookup
closes #341
> feature(lookup): allow updating/replacing recipe lookups

- src/features/lookup_table/use_cases/create_lookup_table.py
check if blueprint from _blueprintPath_ exists when creating lookup table
fail quickly if a user creates an invalid recipe link entity
closes #342
> fix: raise exception if blueprint path not found when creating lookup table

- src/domain_classes/blueprint.py
- src/features/entity/entity_feature.py
- src/features/entity/use_cases/validate_entity.py
- src/tests/unit/test_validate_entity.py
- Allow to pass "as_type" to validation endpoint and validate the entity against this type (instead of type in entity)
- Using the "as_type" argument, also implicitly enables "allow_extra". 
- Causing the validation to allow for extra attributes. 
- Skip "valid child type" check
Be able to validate an entity against a "minimum valid blueprint" (required by UI Plugin)
closes #351
> feature(validation): optionally validate against provided type

- src/features/blueprint/use_cases/resolve_blueprint_use_case.py
- src/tests/bdd/blueprint/resolve_path_to_document.feature
include protocol in path returned
https://github.com/equinor/dm-core-packages/issues/106
> fix: include protocol in path returned from resolve blueprint use case

- src/common/utils/get_storage_recipe.py
- src/home/system/SIMOS/recipe_links/blueprint.json
- src/home/system/SIMOS/recipe_links/default.json
- src/tests/bdd/get_blueprints.feature
rename yaml-view to yaml
needed due to plugin rename, see https://github.com/equinor/dm-core-packages/pull/107/files
part of https://github.com/equinor/dm-core-packages/issues/96
> refactor: rename yaml-view to yaml

- src/common/utils/validators.py
- src/features/entity/use_cases/validate_entity.py
- src/tests/unit/test_validate_entity.py
Moves _recursive_validate_single_attribute and validate_entity into util/validators.py file. The functionality inside the functions is not changed
They will be used outside of the usecase, so it no longer makes sense to store them there
Refs #349
> refactor: move entity validator code into util

- pyproject.toml
running `pytest` failed with moduleNotFound error
> ci: enable pytest debugging

- src/common/responses.py
- src/features/document/document_feature.py
- src/features/document/use_cases/update_document_use_case.py
- src/services/document_service.py
- src/tests/unit/test_complex_arrays.py
- src/tests/unit/test_save.py
- src/tests/unit/test_tree_node_update.py
- Refactor the "/document/" PUT (update) endpoint to be consistent with GET. That is moving "attribute" from a form param to be a part of the reference path parameter.
- Also; small change to make "NotFound" exceptions print stack in debug mode
- Endpoints should have one consistent way to reference documents
closes #373
> refactor: update document uses id_reference in path

- src/domain_classes/ui_recipe.py
- src/home/system/SIMOS/UiRecipe.json
- Add a "dimensions" attribute to uiRecipes
- Need a way to know which recipes support different dimensions
needed for "generic list plugin"
> feature: added dimensions on ui recipes

- src/storage/internal/data_source_repository.py
update data source repository to update data source document in the database if it already exists, instead of replacing the entire database document
bug with import ds command in dm-cli
closes #402
> fix: update data source if it exists

- src/common/utils/get_storage_recipe.py
- src/features/blueprint/use_cases/get_blueprint_use_case.py
- src/tests/bdd/get_blueprints.feature
- Add "List" as a new "default_ui_recipe"
- If blueprints does not have a "*" dimensions uiRecipe, it should default into this.
closes #407
> feature: add generic-list as a default UiRecipe

- src/common/utils/data_structure/find.py
- src/tests/unit/data_structure/find_test.py
Rewrites utils/data_structure/find.py to handle lists with indexes above 9. Also gives better error messages when the object type is primitive or if its type doesn't match the type of the key. Finally, I added types and documentation
Previously, if input key to _get_value was a string "[10]", the index would be calculated as the last number (ie 0) and the call would get incorrect results. Also, the documentation was lacking.
> fix: make find() handle indexing of long lists

- src/common/utils/data_structure/traverse.py
- src/tests/unit/data_structure/traverse_test.py
- src/tests/unit/mock_utils.py
- src/tests/unit/test_get.py
- src/tests/unit/test_tree_node_helpers.py
- src/tests/unit/test_validate_entity.py
Rewrite traverse_compare to something more readable and add checks for missing keys and indices
Add more tests
Fix tests now failing due to the change
traverse_compare didn't catch extra indices or keys
> test: fix holes in traverse_compare

- src/common/utils/data_structure/compare.py
- src/tests/bdd/steps/handle_response.py
- src/tests/unit/test_complex_arrays.py
- src/tests/unit/test_concat_meta_data.py
- src/tests/unit/test_get.py
- src/tests/unit/test_get_extended.py
- src/tests/unit/test_remove.py
- src/tests/unit/test_tree_node_helpers.py
- src/tests/unit/test_tree_node_update.py
Rewrite pretty_eq and adapt all functions using it accordingly
The name "pretty_eq" is misleading, as pretty can mean both beautiful and fairly. Also, the function passes its input to traverse_compare in the wrong order. Finally, the try/catch is no longer needed, since traverse_compare no longer should raise Exceptions
> refactor: rewrite pretty_eq

- src/common/tree_node_serializer.py
- src/common/utils/get_resolved_document_by_id.py
- src/common/utils/package_import.py
- src/common/utils/resolve_reference.py
- src/services/document_service.py
- src/tests/bdd/authentication/access_control.feature
- src/tests/bdd/document/add_file.feature
- src/tests/bdd/document/remove.feature
- src/tests/bdd/document/remove_by_path.feature
- Add more detailed and context aware messages to returned exception messages.
Example on a wrongly named Blueprint
``` 
{
'status': 500,
'type': 'ApplicationException',
'message': "Failed to get document referenced with '/DemoDataSource/recipes'",
'debug': 'Failed to find blueprint with reference \'dmss://system/Plugins/dm-core-plugins/attribute-selector/AttributeSelectorPluginConfig\'. No entity
matches \'Query="name=AttributeSelectorPluginConfig"\' in document \'dmss://system/$3a3c754c-3d40-45f9-871a-1614bb703325.content\'',
'data': None
}
```
- DMSS should tell any user as detailed as possible what is wrong with the models/data
none
> refactor: detailed exception messages in 'resolve_reference()'

- src/common/utils/get_resolved_document_by_id.py
- src/common/utils/resolve_reference.py
- src/domain_classes/tree_node.py
- src/features/document/document_feature.py
- src/features/document/use_cases/update_document_use_case.py
- src/services/document_service.py
- src/tests/unit/common/utils/test_split_reference.py
- src/tests/unit/test_complex_arrays.py
- src/tests/unit/test_get.py
- src/tests/unit/test_reference.py
- src/tests/unit/test_remove.py
- src/tests/unit/test_save.py
- src/tests/unit/test_tree_node_update.py
- DocumentService.update() now understands "ReferenceItems" when getting the "parentNode" (needed since the main target might not exist
- New utility function to split a reference into the different components
- Moved "split_data_source_and _reference" to separate function, since it's needed outside of "resolve_reference()"
- Fixed a bug in unittests where "save()" where never actually tested, since we passed documents by reference. We now operate on a copy, so that "save()" is properly tested.
- Update failed to operate on items in a list (the bug in the tests caused this to go undiscovered)
- The rest follows from that
none
> fix: update_documents now supports new reference scheme

- src/domain_classes/tree_node.py
Adds the "set_uid" function to ListNode
DMSS failed to save a ListNode, since it did not implement the set_uid method
none
> fix: ListNode missing 'set_uid' function

- src/common/utils/get_storage_recipe.py
- src/features/blueprint/use_cases/get_blueprint_use_case.py
- Adds 'attribute-selector' as a default initialUiRecipe
DM framework should work with sane defaults
closes #360
> feat: attribute-selector as default initial recipe

- src/common/tree_node_serializer.py
- src/common/utils/data_structure/find.py
- src/common/utils/get_resolved_document_by_id.py
- src/common/utils/resolve_reference.py
- src/services/document_service.py
- src/storage/data_source_class.py
- src/tests/bdd/document/get.feature
- src/tests/bdd/document/remove_by_path.feature
- src/tests/unit/test_get_document/test_inputs.py
Wanted to test the error messages received when sending an invalid reference to get_document. The tests revealed some bugs and incorrect typing, which has now been fixed. The expection is two failing bdd tests, but since @soofstad is working on the same code, he'll unskip them once he is done
Closes #389
> test: add invalid ref to get document tests

- src/common/utils/resolve_reference.py
- src/tests/unit/common/utils/test_resolve_reference.py
Rewrite the reference_to_reference_items function somewhat. Also add tests for catching this issue in the future
References with queries like `type=test_data/complex/Customer` would fail
> fix: handle more complex reference queries

- src/common/utils/data_structure/has_key_value_pairs.py
- src/common/utils/resolve_reference.py
- src/tests/unit/data_structure/test_is_same.py
- src/tests/unit/test_get_document/test_reference_resolve.py
Renames is_same and refactors QueryItem
The function is_same has a misleading name. And QueryItem is hard to read
> refactor: rename is_same and rewrite queryitem

- src/common/utils/resolve_reference.py
* Respond with not found exception if the resolve reference does not find any document. This is used in the CLI to figure out if a document is already uploaded.
> refactor: change to not found exception

- src/common/tree_node_serializer.py
- src/domain_classes/tree_node.py
* When finding a child inside an array the get_by_ref_part takes in [0] but the key inside each node only keeps 0, so when compare need to remove the brackets.  
* Also added so that we don't try to get blueprint for attributes with attribute type object
> fix: update node list need to remove special symbol before compare to key

- src/app.py
- src/common/tree_node_serializer.py
- src/common/utils/create_entity.py
- src/common/utils/resolve_reference.py
- src/common/utils/validators.py
- src/domain_classes/document_look_up.py
- src/domain_classes/tree_node.py
- src/enums.py
- src/features/blob/use_cases/upload_blob_use_case.py
- src/features/file/file_feature.py
- src/features/file/use_cases/add_file_use_case.py
- src/features/meta/meta_feature.py
- src/features/meta/use_cases/get_meta_use_case.py
- src/home/system/SIMOS/File.json
- src/home/system/SIMOS/recipe_links/file.json
- src/services/document_service.py
- src/storage/data_source_class.py
- src/tests/bdd/file.feature
- src/tests/bdd/steps/api.py
- src/tests/bdd/steps/blobs.py
* Added blueprint attribute type `binary`
* Added `File` blueprint 
* Added `/files/` endpoint to be able to upload files 
* Added `storage_affinity` field to the data source look-up table, to be able to know if the data source id is pointing to a binary 
* Added BDD test that upload binary and create a file using the `/files endpoint
Input parameters to the `/files/` endpoint is: 
* **data_source_id**: what data source to put the file in.
* **file_id**: what id should the file have (we need to provide a id so that the DM CLI can create packages with correct ids) 
* **file**: the actual binary file
> feat: add file support

- src/common/utils/create_entity.py
- src/tests/unit/mock_utils.py
- src/tests/unit/test_create_default_array.py
- src/tests/unit/test_create_entity.py
Before, create entity would create empty dicts for optional attributes. Example:
POST request to http://localhost:5000/api/entity with payload: type: "dmss://WorkflowDS/Blueprints/Job"
Will create
```json
{
"type": "dmss://WorkflowDS/Blueprints/Job",
"status": "Not registered",
"applicationInput": {},
"result": {},
"runner": {}
}
```
after the bug is fixed, optional attributes are not included in the created entity. However, they will be included IF the optional attribute has defined a default value.
Created entity after fix:
```json
{
"type": "dmss://WorkflowDS/Blueprints/Job",
"status": "Not registered"
}
```
closes #462
> fix: bug with create entity

- src/common/utils/get_storage_recipe.py
- src/tests/bdd/get_blueprints.feature
attribute-selector -> view_selector
generic-lsit -> list
> fix: rename plugins according to new naming

- src/common/tree_node_serializer.py
- src/services/document_service.py
- src/tests/bdd/document/update.feature
Update dmss to fix bug with document update. 
the saving of complex attributes when type is "object" did not work correctly. 
example:
1) updating `data-source-name/$7.complexList[0].complexAttribute` with a PUT request (where type of `complexAttribute` is object)
2) GET `data-source-name/$7.complexList[0].complexAttribute` would give error since it did not exist
Also updated tests to make sure that the document are updated correctly.
bug discovered by working on https://github.com/equinor/dm-core-packages/issues/280
> fix: document update bug

- src/common/tree_node_serializer.py
- src/common/utils/get_resolved_document_by_id.py
- src/common/utils/package_import.py
- src/features/document/document_feature.py
- src/features/document/use_cases/get_document_use_case.py
- src/features/entity/use_cases/validate_existing_entity.py
- src/features/export/use_cases/export_use_case.py
- src/features/lookup_table/use_cases/create_lookup_table.py
- src/home/system/SIMOS/Package.json
- src/services/document_service.py
- src/tests/bdd/document/add_document.feature
- src/tests/bdd/document/add_file.feature
- src/tests/bdd/document/get.feature
- src/tests/bdd/document/get_entity_with_optional_attributes.feature
- src/tests/bdd/document/remove_2.feature
- src/tests/unit/test_get_document/test_inputs.py
- src/tests/unit/test_get_document/test_reference_resolve.py
- src/tests/unit/test_tree_functionality/test_tree_dict_conversion.py
*  Update the Package blueprint to set the content attribute to contained true (model contained).
* Rerences with reference type storage are not resolved by default. 
* depth is used to control if references (storage and link) should be resolved (it does not affect contained attributes)
* depth=0 means that if the address is pointing to a reference it will be returned directly without being resolved first.
* depth=1 means that if the address is pointing to a reference it will be resolved before returned. Child references will not be resolved.
* depth=2 means that the entity's direct child references will also be returned.
> BREAKING CHANGE: GET endpoint for documents  - resolve_links is removed
> fix: package content should be storage non-contained

- src/features/blueprint/blueprint_feature.py
- src/features/blueprint/use_cases/get_blueprint_use_case.py
- src/features/entity/entity_feature.py
- src/features/entity/use_cases/validate_entity.py
- src/restful/request_types/shared.py
Custom string types should have the CamelCase notation in order to not be confused with variables. 
Convention is key. Without it we are just swimming in spaghetti.
> refactor: Rename string classes to convention

- src/common/utils/delete_documents.py
- src/storage/data_source_class.py
* Check if an address is pointing to a blob, if so, use `.delete_blob()` method instead of `.delete()`.
Delete blobs.
> fix: delete blobs correctly

- src/common/utils/merge_entity_and_files.py
- src/features/document/document_feature.py
- src/features/document/use_cases/add_document_use_case.py
- src/services/document_service.py
- src/tests/unit/test_reference.py
- src/tests/unit/test_tree_functionality/test_tree_node_update.py
* Moves the add document from the document service to the `add_document_use case`.
* Document service is too big, and getting an overview of the code is therefore more complicated than it should. Isolate all document add functionality to the add document feature (use case). 
> NOTE: this is the first PR of several that will refactor the document service.
> refactor: move add document logic to use case

- src/domain_classes/tree_node.py
- src/features/document/document_feature.py
- src/services/document_service.py
- src/tests/bdd/document/update.feature
- src/tests/bdd/document/update_list.feature
fix bug with update document: when updating an element in a list, a new element was added. Wanted behavior is to have same number of list elements before and after update.
https://github.com/orgs/equinor/projects/189/views/3?pane=issue&itemId=31259287
> fix: bug with updating a list from update document endpoint

- src/features/meta/use_cases/get_meta_use_case.py
- src/services/document_service.py
- src/storage/data_source_class.py
1. Renamed get_access_control to get_lookup because that is what is really is returning.  
2. Changed reference to use get_lookup instead of using the private method _lookup ( ) 
Convention and clear naming is key
> refactor: Rename of a method to fix private method import issue

- src/features/document/document_feature.py
- src/features/document/use_cases/update_document_use_case.py
- src/services/document_service.py
- src/tests/unit/test_complex_arrays.py
- src/tests/unit/test_reference.py
- src/tests/unit/test_save.py
- src/tests/unit/test_tree_functionality/test_tree_node_update.py
* Moves the update document from the document service to the `update_document_use case`.
* Document service is too big, and getting an overview of the code is therefore more complicated than it should be. Isolate all document update functionality to the update document feature (use case). 
> NOTE: this is the first PR of several that will refactor the document service. 
Other PRs:
- https://github.com/equinor/data-modelling-storage-service/pull/510
> refactor: move update document logic to use case instead of document service

- src/features/document/use_cases/add_document_use_case.py
Lower depth used when getting parent. Does not add tests to reproduce the bug, since fixing this bug fast has high priority.
If documentAdd is used to add an optional attribute, we use documentGet to get the parent. The depth was too high, causing non-relevant references to be resolved. When saving later on, the document would be invalid.
> fix(documentAdd): lower depth

- src/authentication/access_control.py
- src/authentication/models.py
- src/domain_classes/document_look_up.py
- src/features/access_control/access_control_feature.py
- src/features/access_control/use_cases/get_acl_use_case.py
- src/features/access_control/use_cases/set_acl_use_case.py
- src/features/lookup_table/use_cases/create_lookup_table.py
- src/features/lookup_table/use_cases/get_lookup_table.py
- src/services/document_service.py
- src/storage/data_source_class.py
- src/storage/internal/data_source_repository.py
- src/tests/bdd/steps/domain.py
Renames some things to be more clear
1.  ACL -> AccessControlList
2.  access_control( ) -> assert_user_has_access( )
3. DEFAULT_ACT -> DEFAULT_ACCESS_CONTROL_LIST
Understanding this as a new guy is really hard, so therefore it is better to write out the names of code. 
Code should be more readable as natural language, and not filled with abbreviations and vague method names.
> refactor: renaming to be more clear

- src/home/system/SIMOS/File.json
closes https://github.com/equinor/dm-core-packages/issues/403
> fix: content in File blueprint should not be model uncontained

- src/features/access_control/access_control_feature.py
- src/features/access_control/use_cases/get_acl_use_case.py
- src/services/document_service.py
* Moves the get acl from the document service to the `get_acl_use_case`.
* Document service is too big, and getting an overview of the code is therefore more complicated than it should be. Isolate all document update functionality to the update document feature (use case). 
Other related PRs:
- https://github.com/equinor/data-modelling-storage-service/pull/510
- https://github.com/equinor/data-modelling-storage-service/pull/513
> refactor: move get acl logic to use case instead of document service

- src/features/document/document_feature.py
- src/features/document/use_cases/check_exsistence_use_case.py
- src/tests/bdd/document/check_existence.feature
- src/tests/bdd/steps/handle_response.py
- src/tests/unit/test_check_existence.py
- src/tests/unit/test_remove.py
Introduces an endpoint for checking if a document exists. The endpoint returns a boolean based on a document address, and a 200 OK for both cases. 
Gives the ability to check if a document exists without creating error logs.
Closes #529
> feat: endpoint for checking if document exist

- src/features/access_control/access_control_feature.py
- src/features/access_control/use_cases/set_acl_use_case.py
- src/services/document_service.py
* Moves the get acl from the document service to the `get_acl_use_case`.
* Document service is too big, and getting an overview of the code is therefore more complicated than it should be. Isolate all document update functionality to the update document feature (use case). 
Other related PRs:
- https://github.com/equinor/data-modelling-storage-service/pull/510
- https://github.com/equinor/data-modelling-storage-service/pull/513
- https://github.com/equinor/data-modelling-storage-service/pull/533
> refactor: move set acl logic to use case instead of document service

- src/common/tree_node_serializer.py
- src/common/utils/get_storage_recipe.py
- src/domain_classes/tree_node.py
- src/features/document/use_cases/add_document_use_case.py
- src/services/document_service.py
- src/tests/bdd/document/reference.feature
- src/tests/unit/test_save.py
- src/tests/unit/test_tree_functionality/blueprints_for_tree_tests.py
Update bdd test to ensure this issue doesn't arise anew. Then fix issue
Started working on this due to documentUpdate not saving to db when input is a reference. Bug seemed caused by the entity getting `storage_contained = False`, which isn't correct. Fixing it caused a new issue with node uids.
> fix: documentUpdate failing for references

- src/features/document/use_cases/add_document_use_case.py
- src/tests/bdd/document/add_attribute_to_document.feature
- src/tests/bdd/document/add_documentwith_optional_attributes.feature
Fixes so that it is possible to add a job to case
Jobs will currently not be added to a case. A job node is created in the backend and saved, but is not appended to the parent Stody.Cases[0] document.
https://github.com/equinor/dm-core-packages/issues/437
> fix: add job to case

- src/features/document/use_cases/add_document_use_case.py
* Use the `get_attribute_by_name` method on the Blueprint class instead of finding the attribute manually. 
* More readable code
> refactor: use method to find attribute

- src/common/utils/data_structure/has_key_value_pairs.py
- src/tests/unit/test_common/test_utils/test_data_structure/test_has_key_value_pairs.py
Merge #552 first
Example 
`
input: 
target {"a": "b"}
content {"x": "y"}
` -> throws
changed to -> `returns false`
The way it was implemented was that 
- if the key in `content` did not exist, the method throws! 
From the naming of the method, and the use, I propose that it should return `false` when the key in `content` does not exist in `target`. 
should return false instead of throw. 
The method `has_key_value_pair()` is a method that is used only once, in `get_child()`, se below, and this implementation should not break the usage of the method
> Feat: error handling in 'has_key_value_pair' method

- src/tests/unit/test_hashing.py
Was digging through unit tests, and found hasing testing to be incomplete. 
- It did only test that equal values with the same salt returned the same hash. 
1. I added the negative test, that for different salts and values, the hash should _not_ be equal. 
3. Test that the output of the salting has the same length, for different input
4. Test that the output does not contain the values or the salt, so that it _actually_ is hashed.
> feat: extend testing coverage of scrypt method to be complete

- docker-compose.override.yml
- src/app.py
- src/config.py
* Be able to add OAUTH_SCOPES defined here: https://portal.azure.com/#view/Microsoft_AAD_RegisteredApps/ApplicationMenuBlade/~/ProtectAnAPI/appId/97a6b5bd-63fb-42c6-bb75-7e5de2394ba0/isMSAApp~/false
> refactor: add oauth scope to swagger

- src/tests/unit/mock_data/mock_blueprint_provider.py
- src/tests/unit/test_tree_functionality/mock_data_for_tree_tests/mock_blueprint_provider_for_tree_tests.py
The unit tests refer sometimes to the CORE SIMOS blueprints.
This is now required to be set explicit in order to make it more readable what blueprints are accessed in the tests. 
It it is not found, then it retuns a `FileNotFoundError`, which is the same as is returned from the real BlueprintProvider. 
#495
> test: be explicit about which SIMOS blueprints are allowed in test-data

- src/tests/unit/test_tree_functionality/test_tree_node_from_dict.py
- src/tests/unit/test_tree_functionality/test_tree_node_to_dict.py
- src/tests/unit/test_tree_functionality/test_tree_node_to_ref_dict.py
❗️No code changes. 
🖖 Split a testing class into two testing classes, as they were testing two different methods, and shared no data
- `tree_node_to_dict`
- `tree_node_to_ref_dict`
➡️ Moved a method `test_tree_node_to_ref_dict()`, which was in `test_from_dict.py` into the correct file
🧘‍♀️ Calm and tranquility, readability, sensibility, and .. affordability(?)
#495
> test: split up two tests into two classes

- src/tests/unit/common/utils/resolve_address/test_resolve_address.py
- src/tests/unit/common/utils/test_create_entity.py
- src/tests/unit/common/utils/validators/test_validate_entity.py
- src/tests/unit/mock_data/mock_blueprint_provider.py
- src/tests/unit/mock_data/mock_document_service.py
- src/tests/unit/services/document_service/test_data_source_and_repositories.py
- src/tests/unit/services/document_service/test_document_service_get_document.py
- src/tests/unit/services/document_service/test_get_extended_blueprint.py
- src/tests/unit/services/document_service/test_reference_resolve.py
- src/tests/unit/services/document_service/test_remove.py
- src/tests/unit/services/document_service/test_save.py
- src/tests/unit/services/document_service/test_update_document_complex_arrays.py
- src/tests/unit/use_cases/test_check_existence.py
- src/tests/unit/use_cases/test_reference.py
In order to make it very clear what CORE: blueprints are accessed in the tests, the `MockBlueprintProvider( )` class is modified to take a list of available simos blueprints as a parameter. 
This is one step on the way to making the mocker be data-less, taking all data as parameters. 
The end goal is that the mocker does not know any data, only gets data as parameters, so the tests themselves provide the data explicitly. 
Many tests are now modified to facilitate this change
#495
> test: made simos blueprints explicit

- src/tests/unit/common/utils/resolve_address/test_resolve_address.py
- src/tests/unit/common/utils/test_create_entity.py
- src/tests/unit/common/utils/validators/test_validate_entity.py
- src/tests/unit/mock_data/mock_blueprint_provider.py
- src/tests/unit/services/document_service/test_data_source_and_repositories.py
- src/tests/unit/services/document_service/test_document_service_get_document.py
- src/tests/unit/services/document_service/test_get_extended_blueprint.py
- src/tests/unit/services/document_service/test_reference_resolve.py
- src/tests/unit/services/document_service/test_remove.py
- src/tests/unit/services/document_service/test_save.py
- src/tests/unit/services/document_service/test_update_document_complex_arrays.py
- src/tests/unit/use_cases/test_check_existence.py
- src/tests/unit/use_cases/test_reference.py
In order to make the mocker reusable we want to make it data-less. 
Thus we remove the references from the `MockBlueprintProvider` and requrie instead each test to specify what blueprints it should have available for testing. 
This makes it very easy to see what blueprints the tests are dependent on. 
#495
> Test: Require list of blueprints as input to the MockBlueprintProvider

- src/common/utils/validators.py
- src/tests/bdd/entity/validate_default_entity.feature
Validates defaults defined in blueprints according to the attribute type
Currently defaults are not checked and invalid defaults can be defined
Closed #567
> fix: validate blueprint attribute default

- src/tests/unit/services/document_service/mock_blueprints/blob_blueprints/blob.blueprint.json
- src/tests/unit/services/document_service/mock_blueprints/blob_blueprints/blobContainer.blueprint.json
- src/tests/unit/services/document_service/mock_blueprints/blob_blueprints/uncontained_blueprint.blueprint.json
- src/tests/unit/services/document_service/mock_blueprints/car_rental_blueprints/CarRental.blueprint.json
- src/tests/unit/services/document_service/mock_blueprints/car_rental_blueprints/Customer.blueprint.json
- src/tests/unit/services/document_service/mock_blueprints/car_rental_blueprints/EngineTest.blueprint.json
- src/tests/unit/services/document_service/mock_blueprints/car_rental_blueprints/FuelPumpTest.blueprint.json
- src/tests/unit/services/document_service/mock_blueprints/car_rental_blueprints/RentalCar.blueprint.json
- src/tests/unit/services/document_service/mock_blueprints/extended_blueprints/ExtendedBlueprint.blueprint.json
- src/tests/unit/services/document_service/mock_blueprints/extended_blueprints/SecondLevelExtendedBlueprint.blueprint.json
- src/tests/unit/services/document_service/test_data_source_and_repositories.py
- src/tests/unit/services/document_service/test_document_service_get_document.py
- src/tests/unit/services/document_service/test_get_extended_blueprint.py
- src/tests/unit/services/document_service/test_reference_resolve.py
Hello. 
Previously we had a huge mocker that had one BIG folder with all the ´mock_blueprints´ for all the tests.
This is not desirable, because we want the unit tests to be as separated as possible. 
Therefore we now move the test data 'down' into the tree structure, closer to the unit tests. 
This is now done for 3 tests. 
1. Created a folder in ´document_service´ unit tests, called ´mock_blueprints´
2. Moved the car example down, which is used by two tests
3. Moved a ´blob_example´ down, which is used by one test
4. Moved ´extended_example´down, which is used by one tes. 
5. Removed the references to blueprint ´basic_blueprint´, because it is a duplicate of ´dmss://system/SIMOS/NamedEntity´ in the tests we are modifying now.
> test: for some test, moving blueprints 'down'

- src/tests/unit/mock_data/mock_recipe_provider.py
- src/tests/unit/mock_data/mock_storage_recipes/mock_storage_recipes.json
This PR is the first of multiple in the quest to make the recipe-provider data-less. 
This first step moves all the storage recipes out from the mocker, instead reading it from file.
> test: mock storage recipe provicer data-less

- src/tests/unit/common/utils/test_create_default_array.py
- src/tests/unit/common/utils/validators/test_validate_entity.py
- src/tests/unit/mock_data/mock_document_service.py
- src/tests/unit/mock_data/mock_recipe_provider.py
- src/tests/unit/services/document_service/test_data_source_and_repositories.py
- src/tests/unit/tree_functionality/test_tree_node_delete.py
- src/tests/unit/tree_functionality/test_tree_node_helpers.py
This is the next PR in line for making the mock-recipe-provider data less. 
So we want each tests to be able to specify the locations for the storage recipes, so that the storage recipes can be moved 'down' to the test. 
1. Created a class, which returns a mocker with the path specified. 
2. Removed calls to the mocker where it was not required.
> test: 👩‍🍳 More on the mock-recipe-provider

- src/authentication/access_control.py
- src/authentication/authentication.py
- src/authentication/models.py
- src/common/utils/mock_token_generator.py
- src/config.py
- src/features/lookup_table/use_cases/create_lookup_table.py
- src/features/lookup_table/use_cases/get_lookup_table.py
- src/services/document_service.py
- src/storage/data_source_class.py
- src/storage/internal/data_source_repository.py
So the default `user` and the default `AccessControlList` were not together with the class, which made it quite messy. 
Now there is separation of concern. 
1. Removed the constant `DEFAULT_ACCESS_CONTROL_LIST`, and moved that into classmethod `AccessControlList.default()`
2. Moved the ´create_access_control_list(user)´ method into the classmethod ´AccessControlList.create_with_owner()´ which is what it actually is used for. 
3. Removed the config `default_user`, and moved that into the classmethod `User.default()`
4. Updated usages for `default_user` and `DEFAULT_ACCESS_CONTROL_LIST`.
> refactor: for separation of concern: moving 'default' and 'constructor' into the classes

- src/authentication/utils.py
- src/tests/unit/authentication/test_utils.py
There is a method which was throwing since it used direct access with [], now switched to `dict.get()` so it does not throw
Also changed `.warn()` -> `.warning()` since `.warn()` is deprecated
> Fix: Not throw on empty role assignments

- src/tests/unit/common/test_address.py
Testing the methods `from_absolute`, `from_relative` and `__init__` of the Address methods
> test: test for address class and classMethods

- src/common/tree_node_serializer.py
- src/domain_classes/tree_node.py
- src/tests/unit/tree_functionality/test_tree_node_helpers.py
So there was like 7-8 methods in tree node that had 0 usages. 
That class is quite large and hard-to-read, so it's nice to clean it up a bit. 
The methods were mostly small helper methods, which can be easily re-written or found in the git log if they are required again 
Because we need to keep it simple, small, and easy to read
> refactor: remove unused methods in tree node

- src/features/document/document_feature.py
- src/features/document/use_cases/add_document_use_case.py
- src/features/document/use_cases/update_document_use_case.py
- src/features/export/use_cases/export_use_case.py
- src/services/document_service.py
- src/tests/bdd/authentication/create_entity_with_user_as_owner.feature
- src/tests/bdd/document/add_file.feature
- src/tests/bdd/document/remove.feature
- src/tests/bdd/document/remove_2.feature
- src/tests/bdd/steps/domain.py
- src/tests/unit/services/document_service/test_data_source_and_repositories.py
- src/tests/unit/services/document_service/test_save.py
- src/tests/unit/tree_functionality/test_tree_node_update.py
- src/tests/unit/use_cases/test_reference.py
- Remove the option for "document_service.save()" to act recursively
NOTE: Some features (export zip and some tests) relied on this feature. The logic has been moved up into these places.
Deprecated feature
closes #617
> refactor: remove last bits on "update_uncontained"

- src/tests/unit/tree_functionality/test_tree_node_helpers.py
- src/tests/unit/tree_functionality/test_tree_node_update.py
We created a blueprint mocker a while ago that was to be used in all the unit tests. 
Now we are starting to use that in the `tree_tests` as well. 
Also some refactoring in the tests to have less duplication of code. More happens in the setup.
> Test: Start of tree-node unit tests refactor

- src/tests/unit/tree_functionality/test_tree_node_delete.py
- src/tests/unit/tree_functionality/test_tree_node_from_dict.py
- src/tests/unit/tree_functionality/test_tree_node_helpers.py
- src/tests/unit/tree_functionality/test_tree_node_to_dict.py
- src/tests/unit/tree_functionality/test_tree_node_update.py
⚠️ review #624 first
1. The file `test_tree_node_helpers` now use the correct mocker. 
2. Further cleaning, by switching to the built-in `self.assertDictEqual` etc
> Test: Refactor finish test tree node helpers and tree node to dict

- src/common/tree/tree_node.py
- src/home/system/SIMOS/Package.json
- src/services/document_service.py
- src/tests/bdd/document/remove_2.feature
- src/tests/unit/common/utils/test_create_default_array.py
- src/tests/unit/use_cases/test_reference.py
- Will now not raise exception if removing an item from a required list
- "content" in Package.json is not required (makes sense, and useful for testing)
- Added a BDD test for this scenario 
It should be allowed to delete items from a list, even if the list attribute itself is required.
closes #632
> fix: remove item from required list attribute

- src/common/providers/storage_recipe_provider.py
- Update the name of the default initial uiRecipe config type from AttributeSelector --> ViewSelector
- Update default initial plugin from view_selector --> view_selector/Tabs (in light of splitting up of the ViewSelector plugin into two plugins)
Default initial uiRecipe fails in frontend
Closes #656
> fix: update default initial uiRecipe from attribute selector

- src/services/document_service/document_service.py
- src/tests/unit/services/document_service/test_remove.py
- src/tests/unit/use_cases/add_document/test_add_reference.py
* Updating entities inside a package fails using an absolute address since the `get_document` method inside the `update_document_use_case` did not resolve the entity that the address is pointing to. If the address is `dmss://DemoDataSource/package/sub-package/entity`, the resolved `node` inside the `document_use_case` become the `sub-package`, but should have been the `entity`. This is solved by setting the depth=1, which means that if the address is pointing to a reference it will be resolved before returned. I just set the depth=1 as default to the `get_document` method, since I think this should be the default behavior.
> fix: set depth to 1 as default for get document method

- src/common/tree/tree_node_serializer.py
Validation checks should return a Validation error. Not a "ValueError" which results in a 500 status code.
API should return helpful errors
none
> fix: validation endpoint properly returns a ValidationException

- src/common/address.py
- src/common/providers/address_resolver/address_resolver.py
- src/features/document/document_feature.py
- src/features/document/use_cases/update_document_use_case.py
- src/services/document_service/document_service.py
- src/tests/bdd/document/get.feature
- src/tests/bdd/document/reference.feature
- src/tests/bdd/document/update.feature
* refactor: `document_service.get_document` to have depth=0 by default 
* refactor: the GET documents endpoint to have depth=0 by default 
* fix: return resolved entity if the address is by path (package/sub-package/entity)
* feat: add validation exceptions to the `update_document_use_case` that throws validation exception if
* 1) try to update a reference with data 
* 2) try to update data with reference
The overall update document rules after this PR is:
```
REFERENCE -> REFERENCE (OK) 
DATA -> DATA  (OK)
DATA -> REFERENCE (ERROR)
REFERENCE -> DATA  (ERROR) 
```
> fix: change to depth 0 as default

- src/common/tree/tree_node_serializer.py
- src/features/document/use_cases/add_document_use_case.py
- src/services/document_service/document_service.py
- src/tests/bdd/document/add_document.feature
- src/tests/unit/common/tree/mock_data/get_mock_nodes.py
- src/tests/unit/services/document_service/mock_blueprints/blob_blueprints/uncontained_blueprint.blueprint.json
- src/tests/unit/services/document_service/test_save.py
Changes the behaviour of document save by creating a (storage) reference to entities only if the entity is storage uncontained.
> fix: transform entities into references when storage uncontained

- src/features/attribute/attribute_feature.py
- src/features/attribute/use_cases/get_attribute_use_case.py
- src/home/system/SIMOS/ViewConfig.json
- GetAttribute endpoint will now resolve references by default, and return "direct address"
Some plugins create views of children that are references. Should be possible to see the actual content.
> feat: get_attribute able to resolve references

- src/features/export/export_feature.py
- src/features/export/use_cases/export_use_case.py
- src/home/system/SIMOS/StorageAttribute.json
- src/home/system/SIMOS/recipe_links/entity.json
- src/home/system/SIMOS/recipe_links/package.json
Trying to export "system/SIMOS" revealed some missing error responses.
When that was added, some invalid blueprints and entities where discovered.
These has now been fixed.
> fix(export): add proper error response on export ++ minor issues

- src/common/entity/validators.py
- src/domain_classes/dimension.py
- src/enums.py
- src/tests/bdd/entity/validate_default_entity.feature
- src/tests/unit/common/tree/test_tree_node_update.py
- A bit more robust handling of "any" type and validation
- "any" is now considered a primitive type, which was needed for being able to update primitive values
- Reorder a list of "if/elif" in validators.py, so that the special case of BlueprintAttributes get's picked out before "any" is picked as a primitive
- The validator did not allow users to update the "default" attribute in BlueprintAttribute with a primitive value
none
> fix: smarter validate attributes of type any

- src/common/providers/address_resolver/path_items.py
- src/common/tree/tree_node.py
- src/tests/bdd/document/add_contained.feature
- src/tests/bdd/document/add_document.feature
- src/tests/bdd/document/add_documentwith_optional_attributes.feature
- src/tests/bdd/document/update_list.feature
- src/tests/unit/common/tree/test_tree_node_helpers.py
- Have Node.node_id() return a valid address for items in a list
When using add_document(), I expect to be able to use the returned address to fetch the newly created entity.
blocking "recurring job handler"
> fix(node): Node.node_id() return invalid address to list elements

- src/app.py
- src/common/entity/validators.py
- src/home/system/SIMOS/Blueprint.json
- src/home/system/SIMOS/Meta.json
- src/home/system/SIMOS/RecipeLink.json
- src/home/system/SIMOS/StorageAttribute.json
- src/home/system/SIMOS/ViewConfig.json
- src/home/system/SIMOS/recipe_links/entity.json
- src/home/system/SIMOS/recipe_links/package.json
- src/home/system/SIMOS/recipe_links/pdf.json
- src/init.sh
- src/tests/bdd/entity/validate_SIMOS.feature
- Add a test that validates the "system/SIMOS"-package
- Fix validation errors
- Add better validation feedback
- disable gunicorn access log (we are already logging with another middleware)
> test: validate core SIMOS package

- src/home/system/SIMOS/UiRecipe.json
So in order to customise the refresh-button we add a showRefreshButton boolean to the uiRecipe. Default to true
> feat: adding showRefreshButton?: bool to uiRecipe

- .github/workflows/on-master-push.yml
No need for it, and it fails to run.
closes #681
> build: remove publish pypi package

- src/services/document_service/delete_documents.py
Ignore empty storage addresses during delete
While deleting packages, it is possible that model contained / storage uncontained content (sub folders) has not yet been uploaded. Trying to delete the sub-folders will throw a NotFoundException. This we should ignore because it means that the subfolders do not exist, and it is safe to delete the parent folder.
Closes https://github.com/equinor/dm-core-packages/issues/858
> fix: skip empty storage references while deleting package

- src/features/attribute/use_cases/get_attribute_use_case.py
Fixes a bug where its not possible to resolve "chained" references.
> fix: get attributes for address that points to reference

- src/common/address.py
- src/common/providers/address_resolver/reference_resolver.py
- src/tests/bdd/document/relative_references.feature
- src/tests/unit/common/test_address.py
* Bug in how the resolve tilde ~ (the fix is to remove the last element in the path, not the first)
* Include the index to the relative path if used inside a list
* Raise exception if going outside document
> fix: resolve tilde correct

- src/authentication/authentication.py
- Remove workaround for assigning role to service principal
- If payload and kwargs contain "roles" we get an exception
none
> fix: don't explicitly set admin role for service principal

- Dockerfile
- docker-compose.ci.yml
- docker-compose.override.yml
- docker-compose.yml
- src/app.py
- src/init.sh
- src/system_DS_template.json
- For the "system.json"-data_source-file, create a template, substitute it's variables with envvars.
- Replace local dev mongoDB image with `bitnami/mongodb:6.0.9`
Overall goal of making environment specific configuration simpler
> build: use a data source template and subst envvars

- docker-compose.override.yml
- src/config.py
Env var used for internal mongoDB should have same name as variable in all other places.
> fix: consistent envvar name

- src/common/tree/tree_node.py
- src/tests/unit/common/tree/mock_data/mock_blueprints/ExtraSpecialChild.blueprint.json
- src/tests/unit/common/tree/test_tree_node_update.py
- Remove children not specified in blueprint when updating node
- Got validation error since complex nested attributes was passed from old node to new (which does not have that attribute)
> fix: remove lingering complex children when changing node type

- src/config.py
- src/domain_classes/dimension.py
- src/features/entity/use_cases/validate_existing_entity_use_case.py
- The fallback recursive limit number (config.MAX_ENTITY_RECURSION_DEPTH) should be bigger than common depth values. If not we get a recursion error on even small depths
> fix: fallback recursive limit should be bigger than common used depth

- src/home/system/SIMOS/Url.json
Adding a url blueprint according to specification
> feat: url blueprint in core

- src/features/document/use_cases/get_document_use_case.py
- src/services/document_service/document_service.py
* Avoid create node tree when getting document that might speed up things a bit
> refactor: skip create node tree when getting documents

- src/common/providers/blueprint_provider.py
- src/features/access_control/access_control_feature.py
- src/features/document/document_feature.py
- src/features/lookup_table/use_cases/create_lookup_table.py
- src/services/document_service/document_service.py
- src/tests/bdd/environment.py
- src/tests/unit/mocks/mock_blueprint_provider.py
- All users now share the same blueprint cache
- Caching was not working as intended. With a new cache for each user and each instance of the DocumentService() (which is created on each request)
related to #770
> perf: blueprint cache shared between users

- src/SIMOS/BlueprintAttribute.json
- src/common/entity/validators.py
- src/common/tree/tree_node.py
- src/domain_classes/blueprint_attribute.py
- src/features/document/use_cases/add_document_use_case.py
- src/tests/bdd/document/add_document.feature
- src/tests/bdd/document/add_file.feature
- src/tests/bdd/document/update_list.feature
- src/tests/bdd/steps/handle_response.py
- src/tests/unit/common/entity/validators/mock_data/CarRental.blueprint.json
- src/tests/unit/common/entity/validators/test_validate_entity.py
- New BlueprintAttribute - attribute "ensureUID"
- This means that any complex attribute, where the attribute definition has this set to "TRUE", MUST have an "_id" key.
- The "add_document" endpoint will inject this id if missing
- Fix some bdd tests to not use the "post file" fixture when not posting a file (should speed up tests)
- An experiment to get static identification for elements in a list
closes #785
> feat: option to enforce uid on all complex children

- src/common/utils/timeit.py
- src/features/search/use_cases/search_use_case/search_use_case.py
- src/init.sh
- Added timit decorator for performance testing
- Increase default timout of gunicorn
- Search endpoint use the same "default_blueprint_provider"
- When running gunicorn with dm-core-packages example data, the validate request times out
related to https://github.com/equinor/dm-core-packages/issues/1307
> fix: gunicorn times out on some slow requests

- poetry.lock
- pyproject.toml
- src/app.py
- src/config.py
* Profile any requests easily, default turned off (need to provide `profile`=true in URL to enable profiling)
* Profile requests and store to disk or Azure blob storage. Default to disk, but if `PROFILING_STORAGE_ACCOUNT` (the connection string to Azure blob storage account) is provided profiles will be uploaded to Azure blob storage.
* Can control what format to store by setting `profile_format`=html|speedscope in URL. Speedscope format is a JSON format, and html is just a simple HTML report.
> feat: add request profiler

- src/features/document/use_cases/add_document_use_case.py
- src/features/document/use_cases/update_document_use_case.py
- src/services/document_service/document_service.py
- src/tests/unit/services/document_service/test_save.py
* Upgrade to a newer `pymongo` version seems to give some performance gain
* Remove saving recursively in the save method (maybe add this later if we need it)
* Remove the `initial` flag from the save method, and let the save method find the parent if any contained node is passed in
> NOTES: needs mongo 3.6 or later (SIMPOS USE 3.4)
Performance before (see tests):
Performance after (see tests):
> refactor: do not save non references recursively

- src/common/tree/tree_node.py
- src/features/document/use_cases/add_document_use_case.py
- src/features/entity/use_cases/validate_existing_entity_use_case.py
- src/services/document_service/document_service.py
- src/tests/bdd/document/add_contained.feature
- src/tests/bdd/document/add_document.feature
- src/tests/bdd/document/add_documentwith_optional_attributes.feature
- src/tests/bdd/document/add_file.feature
- src/tests/bdd/steps/handle_response.py
- "addDocument()" now return the full address to the new entity
- Make sure all branches of the "addDocument" use-case sets UID's
- Failing to get a document during validation should raise ValidationError, not 404.
needed for https://github.com/equinor/dm-core-packages/issues/1308
> feat: addDocument() return full address to the new entity

- src/common/tree/tree_node.py
- src/tests/unit/services/document_service/test_update.py
- Fixes a bug where it was not allowed to leave out primitive values on node.update() with partial=True 
- Simplify node.update() code. No longer need to validate as much, since we do that on a later stage anyway.
closes #810
> fix: partial update only worked with complex

- src/common/providers/address_resolver/path_items.py
- Resolve one reference, check if its a match, and return. Instead of always resolving all references. Pretty big performance improvement when fetching blueprints.
- Unnecessary fetches of all references in a list of references
- Makes the first fetch of blueprints about 50% faster :smile: 
performance
> perf(address_resolver): return early when finding a filter match

- src/common/providers/blueprint_provider.py
- src/common/utils/package_import.py
- src/features/access_control/access_control_feature.py
- src/features/attribute/use_cases/get_attribute_use_case.py
- src/features/blob/use_cases/get_blob_use_case.py
- src/features/blob/use_cases/upload_blob_use_case.py
- src/features/blueprint/use_cases/resolve_blueprint_use_case.py
- src/features/document/document_feature.py
- src/features/document/use_cases/add_raw_use_case.py
- src/features/document/use_cases/get_document_use_case.py
- src/features/document/use_cases/remove_use_case.py
- src/features/export/use_cases/export_meta_use_case.py
- src/features/file/use_cases/add_file_use_case.py
- src/features/lookup_table/use_cases/create_lookup_table.py
- src/features/meta/use_cases/get_meta_use_case.py
- src/features/search/use_cases/search_use_case/search_use_case.py
- src/services/document_service/document_service.py
- src/storage/internal/data_source_repository.py
- src/storage/internal/get_data_source_cached.py
- src/tests/bdd/steps/blobs.py
- src/tests/bdd/steps/data_source.py
- src/tests/bdd/steps/domain.py
- src/tests/bdd/steps/schemas.py
- DataSource caching has not been working for a while. This PR fixes this
- Reduces time for simple single document get in CosmosDB from ~1000ms to ~100ms. This is because on every request the MongoClient has to download meta data from the server before it can execute the request.
> perf: cache on get_data_source

- src/common/entity/validators.py
- src/common/providers/blueprint_provider.py
- src/enums.py
- src/storage/repositories/mongo.py
- src/tests/bdd/document/add_attribute_to_document.feature
- BlueprintProvider has a custom 'get_document' implementation. This allows for some big performance optimizations.
- Drastically improves performance on getting blueprints on a cold cache. Approx 90% faster
performance
> perf: keep fetched blueprints. Custom blueprint 'get_document'

- src/common/providers/address_resolver/address_resolver.py
- src/common/providers/address_resolver/path_items.py
- src/common/providers/address_resolver/reference_resolver.py
- src/features/entity/use_cases/validate_existing_entity_use_case.py
- src/services/document_service/document_service.py
- When calling DocumentService.resolve_document(), a cache for documents are created. The cache lives for this request only.
- The cache stops DMSS fetching the same document from the data_source multiple times.
This improved performance on some request from 82 seconds --> 18,7 seconds
perf
> perf: cache documents in 'resolve_document'

- src/services/database.py
- src/storage/data_source_class.py
- src/storage/internal/redis_client.py
- src/tests/unit/services/document_service/test_data_source_and_repositories.py
- Cache documents in redis (implemented in DataSource)
Loading of a analysis (ULS) goes from 15sec to ~600ms
perf
> feat: cache documents in redis

- src/domain_classes/lookup.py
- src/features/lookup_table/lookup_table_feature.py
- src/features/lookup_table/use_cases/create_lookup_table.py
- src/features/lookup_table/use_cases/refresh_lookup_table.py
- src/tests/bdd/create_lookup.feature
- Adds endpoint to refresh existing "application recipe lookup"
needed for https://github.com/equinor/dm-core-packages/issues/1410
> feat: refresh existing application lookup

- src/common/providers/blueprint_provider.py
- src/services/document_service/document_service.py
Pop cache on blueprint updates 
- Blueprint cache should be reset on changes to blueprints
closes #858
> fix: invalidate BP cache on blueprint updates

- .github/workflows/checks.yml
- Dockerfile
- pyproject.toml
Tries to update pyproject.toml to use poetry v2 format
Broken build
```
Error: The current project could not be installed: No file/folder found for package data-modeling-storage-service
If you do not want to install the current project use --no-root.
If you want to use Poetry only for dependency management but not for packaging, you can disable package mode by setting package-mode = false in your pyproject.toml file.
If you did intend to install the current project, you may need to set `packages` in your pyproject.toml file.
```
> refactor: use poetery v2

- Dockerfile
- src/common/providers/blueprint_provider.py
- src/storage/repositories/mongo.py
Fix this error that happens during the reset application.
The not-so-obvious solution - sometimes the find query inside `BlueprintProvider` returns an empty result, even if the package exists, but if you call it twice it works!
I also adjusted the Mongo `serverSelectionTimeoutMS` and removed the `connectTimeoutMS` to avoid connections problems we have in reset application scripts.
> fix: missing blueprint
