equinor/data-modelling-storage-service

- src/features/export/use_cases/export_use_case.py
load correct meta info when exporting single document and non root package
* refactor the create_zip_export() function - add a utility function to save node to zipfile.
* if the node to export is either a non root package or a single document, the export_meta_use_case is used to load the meta information.
part of zip export
closes #296
> fix: load correct meta info when exporting single document and non root package

- src/home/system/SIMOS/Dependency.json
> fix: change type of version in Dependency.json to string

- src/app.py
- src/tests/bdd/authentication/access_control.feature
- src/tests/bdd/authentication/authentication.feature
- src/tests/bdd/authentication/create_entity_with_user_as_owner.feature
- src/tests/bdd/authentication/personal_access_token.feature
- src/tests/bdd/authentication/set_access_control_list.feature
- src/tests/bdd/blueprint/resolve_path_to_document.feature
- src/tests/bdd/create_lookup.feature
- src/tests/bdd/data_source/crud.feature
- src/tests/bdd/document/add_contained.feature
- src/tests/bdd/document/add_file.feature
- src/tests/bdd/document/add_to_path.feature
- src/tests/bdd/document/get.feature
- src/tests/bdd/document/reference.feature
- src/tests/bdd/document/remove.feature
- src/tests/bdd/document/remove_by_path.feature
- src/tests/bdd/document/subtypes.feature
- src/tests/bdd/document/update.feature
- src/tests/bdd/document/update_with_blob.feature
- src/tests/bdd/export_meta.feature
- src/tests/bdd/export_package.feature
- src/tests/bdd/get_blob.feature
- src/tests/bdd/get_blueprints.feature
- src/tests/bdd/search.feature
- src/tests/bdd/steps/api.py
remove version from api url
api should not be versioned
#324
> fix: remove version from api url

- .github/workflows/publish-to-pypi.yml
> ci: fix publish to pypi bug

- src/features/export/use_cases/export_meta_use_case.py
- src/tests/bdd/export_meta.feature
- Fix a bug where meta from root packages failed to be exported
none
> fix: could not export meta of root packages

- .gitignore
- src/common/tree_node_serializer.py
- src/domain_classes/tree_node.py
- src/features/document/use_cases/update_document_use_case.py
- src/services/document_service.py
- src/tests/bdd/document/update.feature
* Fixes so that it is possible to update list of objects
* Makes it possible to update list of objects
> fix: be able to update list of objects

- README.md
> docs: Fix api docs link

- src/home/system/SIMOS/InlineRecipeViewConfig.json
- src/home/system/SIMOS/ReferenceViewConfig.json
- src/home/system/SIMOS/ViewConfig.json
* Add blueprints for view configs
* Be able to create view configs
> feat: view config blueprints

- src/home/system/SIMOS/InlineRecipeViewConfig.json
- src/home/system/SIMOS/ReferenceViewConfig.json
* Use protocol and absolute path instead of relative
* Does not work with relative paths
> fix: use protocol and complete path

- src/common/responses.py
- src/common/utils/get_document_by_path.py
- src/storage/internal/data_source_repository.py
- Capture and return better error messages on some known issues
- Should be none "unknown 500" errors
none
> fix: handle invalid 'get-by-path'. Handle database error

- src/features/entity/entity_feature.py
- src/features/entity/use_cases/instantiate_entity.py
- src/features/entity/use_cases/validate_entity.py
- src/restful/request_types/shared.py
- src/services/document_service.py
Replace EntityType with Entity, where the latter allow for extra attributes
Stig had already done this on the feat/validate-on-endpoints branch, so I thought I would separate it into its own PR.
> refactor: merge EntityType and Entity

- src/domain_classes/tree_node.py
Fixes lint errors in Node class
Better to use types correctly than to ignore the warnings
> refactor: override entity assignment in Node class

- src/common/utils/validators.py
- src/domain_classes/tree_node.py
I found valid_complex_types quite confusing, so I rewrote it
> refactor: improve valid_complex_type

- src/features/document/use_cases/get_document_use_case.py
- src/home/system/SIMOS/ViewConfig.json
- Raise proper exception on missing key/attribute
- Add optional "label" and "icon" to ViewConfig
none
> feature: add label to ViewConfig

- src/common/tree_node_serializer.py
- src/domain_classes/tree_node.py
- src/features/export/use_cases/export_meta_use_case.py
- src/tests/bdd/document/subtypes.feature
- src/tests/bdd/export_meta.feature
- src/tests/unit/test_tree_node_helpers.py
some bugs have been introduced in the new reference scheme.
This PR fixes some errors and update tests.
related to https://github.com/equinor/dm-cli/issues/81
> fix: bugs with new reference scheme

- src/domain_classes/dependency.py
- src/home/system/SIMOS/Dependency.json
- src/home/system/SIMOS/NamedEntity.json
- src/home/system/SIMOS/Package.json
- src/tests/bdd/export_meta.feature
- src/tests/bdd/get_blueprints.feature
- src/tests/unit/test_concat_meta_data.py
- src/tests/unit/test_create_default_array.py
- src/tests/unit/test_replace_absolute_references_with_alias.py
fix some modeling issues that cause validation to fail when using dm cli commands
https://github.com/equinor/dm-core-packages/issues/189
> fix: modeling issues

- src/services/document_service.py
* Remove should not try to resolve the complete document, since referenced documents can already be deleted
> fix: remove should not resolve complete document

- src/common/responses.py
- src/common/utils/data_structure/is_same.py
- src/common/utils/resolve_reference.py
> refactor: more useful exception on no matching filter

- src/common/tree_node_serializer.py
- src/common/utils/get_resolved_document_by_id.py
- src/common/utils/resolve_reference.py
- src/domain_classes/tree_node.py
- src/services/document_service.py
- src/tests/bdd/document/get.feature
- src/tests/unit/test_get.py
- src/tests/unit/test_save.py
Add testing of the depth parameter. Not everything worked well, so had to do some rewriting.
We need to test that the depth parameter works as intended
Refs #389
> test: add get_document with depth tests

- src/features/lookup_table/lookup_table_feature.py
- src/features/lookup_table/use_cases/create_lookup_table.py
- src/tests/bdd/create_lookup.feature
- src/tests/bdd/steps/schemas.py
update the create lookup table use case to handle several to "reciple links" pacakges.
https://github.com/equinor/dm-cli/issues/90
> feat: update the create lookup table use case to handle several to "recipe links" pacakges

- src/common/utils/resolve_reference.py
- src/services/document_service.py
- src/tests/unit/common/utils/test_split_reference.py
- Fixes some unresolved comments from #429 
- better documentation and test coverage
none
> refactor: documentation and test coverage for ref_split

- src/common/utils/delete_documents.py
- src/services/document_service.py
- src/tests/unit/test_remove.py
- refactors test_remove to use a shared setup
- add test for deleting a list attribute
- fix issues revealed by the above mentioned test
It should be possible to delete attributes of type list
Refs #414
> fix: delete nested list

- src/app.py
- src/common/tree_node_serializer.py
- src/features/attribute/attribute_feature.py
- src/features/attribute/use_cases/get_attribute_use_case.py
- src/tests/unit/test_tree_node_helpers.py
* Add endpoint to get attribute for a given reference
> feat: attribute endpoint

- src/home/system/SIMOS/UiRecipe.json
> fix: make recipe plugin mandatory

- src/common/utils/get_resolved_document_by_id.py
- src/services/document_service.py
rename resolve_document to resolve_references_in_entity
#465
> refactor: rename resolve_document to resolve_references_in_entity

- src/home/system/SIMOS/ViewConfig.json
> fix: add type attribute to ViewConfig blueprint

- src/domain_classes/tree_node.py
- src/services/document_service.py
- src/tests/unit/test_tree_functionality/blueprints_for_tree_tests.py
- src/tests/unit/test_tree_functionality/test_tree_node_helpers.py
Remove the name attribute from the Node class.
closes #401
> fix: remove name attribute from Node class

- src/common/utils/arrays.py
- src/common/utils/create_entity.py
- src/common/utils/string_helpers.py
- src/domain_classes/dimension.py
- src/features/entity/entity_feature.py
- src/tests/bdd/entity/instantiate_entity.feature
- src/tests/bdd/entity/validate_existing_entity.feature
- src/tests/bdd/entity/validate_non_existing_entity.feature
- src/tests/unit/test_create_default_array.py
- src/tests/unit/test_create_entity.py
- a refactor of the create_default_array function - it has been moved to a new file and simplified a bit.
- refactor of tests
- bdd test for instantiate entity that was missing
> refactor: create_default_array

- src/common/tree_node_serializer.py
- src/features/document/document_feature.py
- src/features/reference/reference_feature.py
- src/features/reference/use_cases/insert_reference_use_case.py
- src/services/document_service.py
- src/tests/bdd/document/reference.feature
- src/tests/unit/test_reference.py
- src/tests/unit/test_tree_functionality/blueprints_for_tree_tests.py
- src/tests/unit/test_tree_functionality/get_node_for_tree_tests.py
- src/tests/unit/test_tree_functionality/test_tree_dict_conversion.py
Document add endpoint can be used instead of the insert reference endpoint.
closes #490
> fix: remove insert_reference

- src/services/document_service.py
- src/tests/bdd/document/add_documentwith_optional_attributes.feature
- src/tests/bdd/document/add_file.feature
fix bug in document add endpoint when adding optional attribute that does not exist
https://github.com/equinor/data-modelling-storage-service/issues/485
> fix: bug with document add endpoint for optional attributes

- src/features/export/export_feature.py
- src/features/file/file_feature.py
- src/features/health_check/health_check_feature.py
- src/features/lookup_table/lookup_table_feature.py
- src/features/meta/meta_feature.py
- src/features/personal_access_token/personal_access_token_feature.py
- src/features/search/search_feature.py
- src/features/whoami/whoami_feature.py
This is a part of "Den store Dokumentasjonsdagen". 
Adding docstrings to DMSS endpoints. 
https://github.com/orgs/equinor/projects/189?pane=issue&itemId=35829553
> Docs:  Docstrings for endpoints

- src/features/document/document_feature.py
- src/features/entity/entity_feature.py
- src/features/export/export_feature.py
- src/features/file/file_feature.py
- src/features/health_check/health_check_feature.py
- src/features/lookup_table/lookup_table_feature.py
- src/features/meta/meta_feature.py
- src/features/search/search_feature.py
- src/features/whoami/whoami_feature.py
Comments that were suggested in last PR were not fixed before merge
> Docs: Comment fixes

- src/features/access_control/access_control_feature.py
- src/features/attribute/attribute_feature.py
- src/features/blob/blob_feature.py
- src/features/blueprint/blueprint_feature.py
- src/features/datasource/datasource_feature.py
- src/features/document/document_feature.py
- src/features/entity/entity_feature.py
Docstrings for rest of HTTP endpoints
> docs: adding docstrings to the rest of the endpoints

- src/features/search/use_cases/search_use_case.py
- src/tests/bdd/search.feature
Refactors the search-use-case method which was messy and had code duplications. 
Not it is hopefully more clear and straight-forward. 
1. Removed method output variable in python which is a true code smell. 
2. Removed else-statement, which kinda clutters the code 
3. Removed duplicate for loops with calls to same function, now only one. 
See why here: 
https://www.youtube.com/watch?v=eUhWKe1ZqKY
> refactor: refactored search-use-case

- README.md
- src/tests/README.md
> docs: update reset command in readme

- src/common/utils/resolve_address.py
One line: using get_lookup() instead of _lookup() which is a private variable
> refactor: using getter

- README.md
A copy command did not do the expected, and the result was that the rest of the setup failed. 
Now I changed it to something that works.
> docs: Setup steps in DMSS readme did not work, now they do

- .github/workflows/checks.yml
- Dockerfile
- src/init.sh
* Populate data source from environment variable called `DATA_SOURCE_FILES` (maybe there will be more than one data source in the future)
* Reset the data source at startup
> feat: populate data source at startup using environment variable

- src/authentication/authentication.py
* Allow the Application to log in as itself (in Github action)
> feat: support app registration with a Federated Credential to login

- src/tests/unit/services/document_service/test_remove.py
Found two testing methods that seem to be the exact same test case. 
Removed one of them. Renamed the method name of the other 
Want the reviewer to double check that this is correct.
> test: removed duplicate methods testing the same thing. 

- src/tests/unit/authentication/test_user.py
A test file for testing the user file
> test: added test for the USER class

- src/tests/unit/authentication/test_access_control_list.py
- src/tests/unit/authentication/test_user.py
⚠️ First merge #590 
Adding a test file for the access control list, with test cases for initialization and the ´dict()´ method
> Test: Test cases for the Access Control List

- src/authentication/models.py
- src/tests/unit/authentication/test_access_control.py
- src/tests/unit/authentication/test_access_control_list.py
- src/tests/unit/authentication/test_user.py
⚠️ Dependent on #590, #591
Had no tests for the access control, which is an important part of the program. 
So here it is
> Unit Tests for Access Control itself

- src/authentication/models.py
- src/tests/unit/authentication/test_pat_data.py
1. Changed a type hint in PAT data. UUID --> str, becaue it is actually an instance of str. 
2. Added a unit testing file for the PAT data
> test: added tests for pat data, also fixed type hinting to be correct

- src/home/system/SIMOS/ViewConfig.json
Adds "roles" attribute to ViewConfig attribute type 
Make role based filtering possible in the frontend
> feat: roles attribute on view config

- src/common/utils/logging.py
> refactor: remove unused logger 

- src/features/document/use_cases/add_document_use_case.py
* Avoid resolving more than needed
> fix: adjust depth to avoid resolve more than needed

- src/tests/unit/tree_functionality/test_tree_node_update.py
Further improvements of the unit tests tree update. 
Instead of so much code duplication, i used the deepcopy
Also changed the assert statements to self.assert(), which is the unittest standard. 
And instead of self-written get and print diff, we use self.assertDictEqual
> Test: More tree unit test refactoring

- src/common/utils/create_entity.py
Was not used, so remove it
Keep it simple, stupid <3
> refactor: remove unused stuff in create_entity.py

- src/tests/unit/common/utils/test_sort_dtos_by_attribute.py
Adding unit tests for a method
> test: unit tests for sort dtos

- src/common/entity/is_reference.py
- src/common/providers/reference_resolver.py
- src/tests/unit/common/entity/test_is_reference.py
> test: unit tests for is_reference and minor changes

- src/tests/unit/services/document_service/mock_blueprints/arrays/basic.blueprint.json
- src/tests/unit/services/document_service/mock_blueprints/arrays/higher_rank_array.blueprint.json
- src/tests/unit/services/document_service/mock_blueprints/arrays/package.blueprint.json
- src/tests/unit/services/document_service/test_update_document_complex_arrays.py
1. Removed a perma-skipped test. 
2. Made test use the general mocker istead of re-implement. 
3. Moved blueprints out and into separate folder for easier readability
> test: refactor complex arrays

- src/home/system/SIMOS/File.json
> refactor: make author optional

- src/services/document_service/document_service.py
Fix that skips checking of duplicate name in empty references
If references are attempted created before the document itself is created, then we assume that you are an expert and know what you are doing.
> fix: defer checking of duplicate name in empty package references

- src/features/document/use_cases/add_document_use_case.py
- src/tests/bdd/document/add_documentwith_optional_attributes.feature
> feat: add optional empty list

- src/tests/bdd/entity/validate_default_entity.feature
> tests: fix test

- src/home/system/SIMOS/UiRecipe.json
> feat: refresh button not show by default

- src/home/system/SIMOS/ViewConfig.json
Adds the possibility to set refreshButton in viewConfig
> feat: refreshButton in ViewConfig

- src/home/system/SIMOS/Application.json
- src/home/system/SIMOS/Role.json
- Update Application blueprint and add blueprint for Role
> feat: role blueprint

- src/home/system/SIMOS/Application.json
> fix: bad type format

- src/common/address.py
- src/common/providers/address_resolver/reference_resolver.py
- src/tests/bdd/document/relative_references.feature
* Feat: Be able to use `~´  inside an address to point/go upwards to attributes.
> feat: relative references

- src/features/file/use_cases/add_file_use_case.py
- src/tests/bdd/file.feature
* Set filetype instead of mime type (content type)
> fix: set filetype and not mime type

- src/features/access_control/access_control_feature.py
Merge "data_source" and "documentId" to one parameter for the ACL endpoints.
Consistency between endpoints
> refactor: merge DS and docID in ACL endpoints

- src/common/entity/validators.py
- src/tests/unit/common/entity/validators/mock_data/EngineTest.blueprint.json
- src/tests/unit/common/entity/validators/mock_data/Layout.enum.json
- src/tests/unit/common/entity/validators/test_validate_entity.py
Validate enums
Missing validation
> feat: validate enums

- src/common/address.py
> fix: typo in f string

- src/SIMOS/Entity.json
- src/tests/bdd/get_blueprints.feature
> adding optional label to Entity.

- src/common/providers/blueprint_provider.py
- src/services/document_service/document_service.py
- src/tests/bdd/authentication/access_control.feature
- src/tests/bdd/document/add_file.feature
- src/tests/bdd/document/remove.feature
- src/tests/bdd/document/remove_2.feature
- More informative error response
- Inner exceptions are added as data to outer exceptions
> fix: better error on not found blueprint

- src/SIMOS/Meta.json
Added some more attributes in Meta blueprint
Needed for https://github.com/equinor/dm-core-packages/issues/1148
> feat: more attributes in SIMOS/Meta

- docker-compose.yml
- src/common/address.py
- src/common/providers/address_resolver/reference_resolver.py
- src/common/utils/update_nested_dict.py
- src/features/document/use_cases/get_document_use_case.py
- src/services/document_service/document_service.py
* Improve performance by only resolve relevant references
> refactor: only resolve relevant references

- src/config.py
> fix: increase default cache size

- src/features/document/use_cases/check_exsistence_use_case.py
* Change to resolve_document for better performance
> chore: change to resolve document for better performance

- src/app.py
* Add query param called `profile_time_limit`, if specified (in seconds), only requests that are over the given time limit are stored. E.g `http://localhost:5002/api/documents/dmss://MSDS/$_asgb_platform_model_id.sensorData.tasks.fetchSignals%5B0%5D.sce?partial_update=true&profile=true&profile_time_limit=0.3` (only store profile if time limit is above 300 ms) 
* Also added so that profiles are sent to Azure as background tasks 🚤 
* Changed a bit on the file name for profiles stored 
date - environment - request time - method - url ....
> feat: add option to set time limit, better filename and async uploading of profiles to Azure blob storage

- src/SIMOS/Meta.json
- src/common/providers/blueprint_provider.py
> feat: add versionNote to Meta. Reduce BP provider logging

- README.md
> chore: add compliant badge

- src/common/providers/address_resolver/reference_resolver.py
- src/features/entity/use_cases/validate_existing_entity_use_case.py
Add some context to the error message returned when a "resolve address" failes
> fix: more info on 'failed to resolve reference'

- src/init.sh
> fix: increase gunicorn timeout to 180s

- .github/workflows/on-master-push.yml
- README.md
part of https://github.com/equinor/dm-docs/issues/48
> docs: README to be up-to-date

- src/SIMOS/RecipeLink.json
> feat: optional name and description to RecipeLink

- docker-compose.override.yml
- docker-compose.yml
- poetry.lock
- pyproject.toml
- src/app.py
- src/config.py
- src/services/database.py
- src/storage/data_source_class.py
- src/storage/internal/data_source_repository.py
- src/storage/internal/lookup_tables.py
- src/storage/internal/personal_access_tokens.py
- src/storage/internal/redis_client.py
- src/tests/bdd/data_source/crud.feature
- src/tests/bdd/steps/data_source.py
- src/tests/bdd/steps/domain.py
- src/tests/test_helpers/wipe_db.py
- src/tests/unit/services/document_service/test_data_source_and_repositories.py
Replaces the internal mongoDB with a RedisDB. This effects a lot of stuff, but mainly it's a huge performance increase
perf
> perf: move internal db to memory-DB

- src/storage/internal/data_source_repository.py
Bug introduced when replacing internalDB from mongo to redis
> fix: create datasource should be replace existing

- src/storage/repositories/mongo.py
- Adds retries to some mongo repository methods. (Will retry up to 3 times, with 3sec delay)
- Azure CosmosDB has strict rate-limiting, and often returns 429(Too Many Requests)
> fix(mongo): retry failed requests

- src/common/tree/tree_node.py
- src/features/export/use_cases/export_use_case.py
- src/services/document_service/document_service.py
- src/storage/data_source_class.py
- src/storage/data_source_interface.py
- src/storage/repositories/azure_blob.py
- src/storage/repositories/file.py
- src/storage/repositories/mongo.py
- src/storage/repositories/zip/zip_file_client.py
- src/storage/repository_interface.py
- Fix the exporting
- The file structure of exported packages were all wrong, and did not contain blobs 
closes #838
> fix: export entities and folders
